version: '3.9'

services:
  web_server:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./index.php:/var/www/index.php
      - ./src:/var/www/src
      - ./docker/nginx/simple_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm

  php_fpm:
    build:
      context: .
      target: symfony_php
    volumes:
      - ./index.php:/var/www/index.php
      - ./src:/var/www/src
